---
title: "2.0.1_Autoimmune_Disease_LCCs"
author: "Ursula Widocki"
date: "8/15/2021"
output: html_document
---

###########################################################################################################
#
# This markdown computes LCCs of each autoimmune disease
#
###########################################################################################################

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(data.table)
`%ni%` <- Negate(`%in%`)
library(igraph)
library(magrittr)
library(ggraph)
library(BiRewire)
library(superheat)
library(NetSci)
source("/Users/ursulawidocki/Desktop/BarabasiLab//NetMedTools.R")
```

```{r}
# Read in immunity genes (just in case you want to incorporate them)
immune_data = read.table("/Users/ursulawidocki/Desktop/BarabasiLab/Data/immunity_genes_all.tsv", 
                        sep = "\t", stringsAsFactors = F, header = T, row.names = 1)
immune_data <- immune_data %>% # remove ReactomeDB
  select(!c(ReactomePathwayInnate, ReactomePathIDInnate, ReactomeDB, isInnateReactome, ReactomePathwayAdaptive, ReactomePathIDAdaptive, isAdaptiveReactome))

# Read in PPI data
ppi <- read.csv('/Users/ursulawidocki/Desktop/BarabasiLab/Vaccine/Data/PPI_Symbol_Entrez.csv')
ppi_df <- ppi[,c("Symbol_A", "Symbol_B")]

ppi_df = ppi_df[!(!is.na(ppi_df$Symbol_B) & ppi_df$Symbol_B ==""), ]
ppi_df = ppi_df[!(!is.na(ppi_df$Symbol_A) & ppi_df$Symbol_A ==""), ]

ppi_df$value = 1
ppi_df = ppi_df %>% unique()
ppi_g <- igraph::graph_from_data_frame(ppi_df, directed = F)
ppi_g %<>% simplify()

ppi_degree_df = data.frame(Degree = degree(graph = ppi_g)) %>%
  mutate(Gene = row.names(.))

GDA_data = read.table("/Users/ursulawidocki/Desktop/BarabasiLab/Data/GDA_auto.csv", 
                        sep = ",", stringsAsFactors = F, header = T) # has isAutoimmune col
# select disease that have some form of Strong or Weak evidence and have more than 5 disease genes
GDA_auto <- GDA_data %>%
  filter(Strong > 0 | 
           Weak > 0) %>%
  filter(hgnc_symbol %in% V(ppi_g)$name)%>% 
  group_by(NewName) %>%
  mutate(Total_Genes = n()) %>%
  filter(Total_Genes > 5) %>%
  filter(isAutoimmune == 1) %>%
  dplyr::select(NewName, hgnc_symbol) %>%
  unique()
```


# LCCs
```{r}
# Computes and Evaluates LCC of each disease

autoimmune_dis_list = unique(GDA_auto$NewName)

col_labels <- c("Disease", "LCCsize", "p_val", "Mean", "SD", "Z", "num_genes")
autoimmune_LCC_df = data.frame(matrix(ncol = length(col_labels), nrow = 0))
colnames(autoimmune_LCC_df) = col_labels

# for each disease
for (dis in autoimmune_dis_list){
  print(dis)
  dis_genes = GDA_auto %>% filter(NewName == dis) # get all disease genes
  dis_genes = dis_genes$hgnc_symbol
  dis_genes = dis_genes[dis_genes %in% V(ppi_g)$name] # filter for those in PPI
  
  LCC_dis = LCC_signif(G = ppi_g, targets = dis_genes, 
                       num_bins_degree_G = 1, min_bin_degree = 1, iter = 1000)
  
  # add info to df
  new_line <- c(dis, LCC_dis$size, LCC_dis$p_val, LCC_dis$emp_mean, 
                LCC_dis$emp_SD, LCC_dis$Z, length(dis_genes))
  autoimmune_LCC_df[nrow(autoimmune_LCC_df) + 1,] <- new_line
  
  # print LCC hist
  #if(LCC_dis$p_val < 0.05){
  #  lim = c(LCC_dis$size, LCC_dis$distribution)
  #  hist(LCC_dis$distribution, main = paste0(dis, " Empirical LCC Distribution"), 
  #      xlim = c(min(lim - 50), max(lim + 50)), col = 'gray75', 
  #       ylab = "", breaks = 20)
    
   # abline(v = LCC_dis$size, col = "red")
  #}
  
  # print degree distribution of LCC genes
  
  # print degree distribution of non-LCC genes
}

autoimmune_LCC_df$LCCsize <- as.numeric(autoimmune_LCC_df$LCCsize)
autoimmune_LCC_df$p_val <- as.numeric(autoimmune_LCC_df$p_val)
autoimmune_LCC_df$Mean <- as.numeric(autoimmune_LCC_df$Mean)
autoimmune_LCC_df$SD <- as.numeric(autoimmune_LCC_df$SD)
autoimmune_LCC_df$Z <- as.numeric(autoimmune_LCC_df$Z)
autoimmune_LCC_df$num_genes <- as.numeric(autoimmune_LCC_df$num_genes)

rownames(autoimmune_LCC_df) <- autoimmune_LCC_df$Disease
autoimmune_LCC_df$signif <- ifelse(autoimmune_LCC_df$p_val < 0.1, "signif", "nonsignif")
autoimmune_LCC_df$LCC_prop <- autoimmune_LCC_df$LCCsize / autoimmune_LCC_df$num_genes

```

```{r}
# save LCC info so you don't need to run this again...

#write.table(autoimmune_LCC_df, file = "/Users/ursulawidocki/Desktop/BarabasiLab/Data/AutoDis_LCCs.tsv", sep = "\t", row.names = F, col.names = T)
```

|
|
|
V
```{r}
autoimmune_LCC_df = read.table("/Users/ursulawidocki/Desktop/BarabasiLab/Data/AutoDis_LCCs.tsv", 
                        sep = "\t", stringsAsFactors = F, header = T)
rownames(autoimmune_LCC_df) <- autoimmune_LCC_df$Disease
```


```{r}
# Vizualize the disease LCCs and p-value

autoimmune_LCC_df <- autoimmune_LCC_df %>% 
  mutate(padj = p.adjust(p_val, method = "fdr")) %>%
  mutate(signif = ifelse(padj < 0.05, "padj < 0.05", "padj > 0.05"))

autoimmune_LCC_df %<>%
  arrange(desc(padj))
autoimmune_LCC_df$Disease = factor(row.names(autoimmune_LCC_df), 
                                   levels = row.names(autoimmune_LCC_df))
  
ggplot(autoimmune_LCC_df) + # autoimmune_LCC_df %>% dplyr::arrange(padj)
  aes(x = Disease, y = -log10(padj), colour = signif, size = LCCsize) +
  geom_point(shape = "circle", alpha = 0.5) +
  scale_size(range = c(0, 10)) +
  labs(x = "Disease", y = "-log10 adj p-value", title = "Statistical Significance of Autoimmune Disease Modules") +
  scale_color_manual(values = c("padj < 0.05" = "turquoise3", "padj > 0.05" = "tomato1")) +
  scale_y_log10() +
  ggplot2::scale_y_continuous(limits = c(0, 5)) + 
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "bottom") +
  geom_hline(yintercept = -log10(0.05), color = "red") +
  coord_flip()

#ggplot(autoimmune_LCC_df %>% dplyr::arrange(p_val)) +
#  aes(x = Disease, y = p_val, colour = signif, size = LCCsize) +
#  geom_point(shape = "circle", fill = "#112446", alpha = 0.4) +
#  labs(x = "Disease", y = "LCC p-value") +
#  scale_color_hue(direction = 1) +
#  theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "bottom") +
#  geom_hline(yintercept = 0.1, color = "red")

#ggplot(autoimmune_LCC_df %>% dplyr::arrange(padj)) +
#  aes(x = Disease, y = -log10(padj), colour = signif, size = LCCsize) +
#  geom_point(shape = "circle", fill = "#112446", alpha = 0.4) +
#  labs(x = "Disease", y = "LCC -log10 adjusted p-value", title = "Statistical Significance of Autoimmune Disease Modules") +
#  scale_color_hue(direction = 1) +
#  scale_y_log10() +
#  theme_minimal() +
#  theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "bottom") +
#  geom_hline(yintercept = -log10(0.05), color = "red")

```

```{r}
# make viz where size of LCC if proportion of LCCsize/numDisGenes 
# and maybe even make this its own viz

ggplot(autoimmune_LCC_df %>% dplyr::arrange(desc(padj))) +
  aes(x = Disease, y = LCC_prop, colour = signif, size = LCC_prop) +
  geom_point(shape = "circle", fill = "#112446", alpha = 0.5) +
  scale_color_manual(values = c("padj < 0.05" = "turquoise3", "padj > 0.05" = "tomato1")) +
  labs(x = "", y = "LCC size / Total Number Disease Genes", title = "Proportion of Disease Genes in LCC per Autoimmune Disease") +
  theme_minimal() +
  theme(legend.position = "bottom", axis.text = element_text(size = 15)) +
  coord_flip()

```

```{r}
# make visualization of the number of genes per disease with LCC size as point size

disease_gene_assoc <- GDA_auto %>%
  group_by(NewName) %>%
  summarize(n = n())
rownames(disease_gene_assoc) = disease_gene_assoc$NewName

LCC_info <- autoimmune_LCC_df %>% select(Disease, LCCsize)
colnames(LCC_info)[1] <- "NewName"
disease_gene_assoc <- merge(disease_gene_assoc, LCC_info, by = "NewName")

ggplot(disease_gene_assoc) +
  aes(x = reorder(NewName, n), y = n, size = LCCsize) +
  geom_point(shape = "circle", fill = "tomato1", color = "tomato1", alpha = 0.4) +
  labs(title = "Number of Disease Genes per Autoimmune Disease", x = "Autoimmune Disease", y = "Number of Disease Genes") +
  ggplot2::scale_y_continuous(limits = c(0, 415)) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "bottom")

# same plot but vertical
ggplot(disease_gene_assoc) +
  aes(x = reorder(NewName, n), y = n, size = LCCsize) +
  geom_point(shape = "circle", fill = "tomato1", color = "tomato1", alpha = 0.4) +
  labs(title = "Number of Disease Genes per Autoimmune Disease", x = "Autoimmune Disease", y = "Number of Disease Genes") +
  theme_minimal() +
  #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  coord_flip()
```

```{r}
# read in autoimmune disease data to get dis with stat signif module
autoimmune_LCC_df = read.table("/Users/ursulawidocki/Desktop/BarabasiLab/Data/AutoDis_LCCs.tsv", 
                               sep = "\t", stringsAsFactors = F, header = T)
rownames(autoimmune_LCC_df) <- autoimmune_LCC_df$Disease

autoimmune_LCC_df <- autoimmune_LCC_df %>% 
  mutate(padj = p.adjust(p_val, method = "fdr")) %>%
  mutate(signif = ifelse(padj < 0.05, "padj < 0.05", "padj > 0.05"))

signif_diseases <- autoimmune_LCC_df %>%
  filter(signif == "padj < 0.05")

length(unique(signif_diseases$Disease))
```





## Separation between diseases

```{r}
# calculate significance of separation of all diseases
###### with only stat signif diseases, see chunks below

sep_signif <- NetSci::separation_Significance(ppi_g,
                                    ST = GDA_auto,
                                    Threads = 10,
                                    N = 1000,
                                    correct_by_target = TRUE)

sep_signif_whole_ppi <- NetSci::separation_Significance(ppi_g,
                                    ST = GDA_auto,
                                    Threads = 10,
                                    N = 1000,
                                    correct_by_target = F)

write.table(sep_signif_whole_ppi, "/Users/ursulawidocki/Desktop/BarabasiLab/Data/Autoimmune_Sep_Signif_whole_ppi.tsv", sep = "\t", row.names = F, col.names = T)
```

```{r}
sep_signif_whole_ppi <- sep_signif_whole_ppi %>% 
  mutate(padj = p.adjust(pvalue_lt, method = "fdr")) %>%
  mutate(signif = ifelse(padj < 0.05, "padj < 0.05", "padj > 0.05"))

#write.table(sep_signif_whole_ppi, "/Users/ursulawidocki/Desktop/BarabasiLab/Data/Autoimmune_Sep_Signif_whole_ppi.tsv", sep = "\t", row.names = F, col.names = T)
```

```{r}
#sep_signif_whole_ppi <- read.table("/Users/ursulawidocki/Desktop/BarabasiLab/Data/Autoimmune_Sep_Signif_whole_ppi.tsv", sep = "\t", row.names = F, col.names = T)
```


```{r}
## Separation only between stat signif disease modules
stat_signif_diseases <- signif_diseases$Disease

# Calculate separation between signif diseases
signif_dis_GDA <- GDA_auto %>%
  filter(NewName %in% stat_signif_diseases)
sep_signif_dis <- NetSci::separation_Significance(ppi_g,
                                    ST = signif_dis_GDA,
                                    Threads = 5,
                                    N = 1000,
                                    correct_by_target = F)
```

```{r}
# Note significance of edges

sep_signif_dis <- sep_signif_dis %>% 
  mutate(padj = p.adjust(pvalue_lt, method = "fdr")) %>%
  mutate(signif = ifelse(padj < 0.05, "padj < 0.05", "padj > 0.05"))

signif_sep <- sep_signif_dis %>%
  filter(padj < 0.05)
signif_sep <- signif_sep %>% select("x", "y", "Sab")

# all stat signif edges are negative

```


```{r}
## Plot Sab graph with stat signif edges

g_sep <- graph.data.frame(signif_sep, directed = F)
sep_matrix <- get.adjacency(g_sep, sparse = FALSE, attr='Sab')
g_sep = graph_from_adjacency_matrix(abs(sep_matrix), mode = "undirected", weighted = TRUE)

V(g_sep)$degree = degree(g_sep)

#isolated = which(degree(g_sep) == 0)
#g_sep = delete.vertices(g_sep, isolated)

# plot
ggraph(g_sep, "fr") + # "stress"
  #geom_edge_hive(aes(width = weight,
  #                  alpha = weight)) +
  geom_edge_hive() +
  geom_node_point(aes(size = degree), color = "turquoise3", alpha = 0.7) +
  geom_node_text(aes(label = name),
                 size = 3) #+
  #scale_edge_width(range = c(0.1, 1)) +
  #scale_color_hue(l  = c(75), c = 35) + 
  #scale_edge_width(range = c(0, 3))+
  #scale_size(range = c(2, 8)) + 
  #theme_void()

```


```{r}
# look at Sab with disease categories

x = GDA_data %>% select(NewName, DescriptorName)

tmp = GDA_data$DescriptorName %>% 
  stringr::str_split("\\|", simplify = TRUE) %>%
  as.data.frame()
x = cbind(x, tmp) %>%
  pivot_longer(-NewName) %>% 
  filter(value != "") %>%
  filter(name != "DescriptorName") %>% 
  select(-name) %>%
  unique()

# gets disease category 
categ_dis = x %>% 
  group_by(value) %>%
  mutate(n = n()) %>%
  ungroup() %>% 
  group_by(NewName) %>% 
  mutate(x = max(n)) %>%
  filter(n == x) %>%
  select(-c(n,x)) %>%
  filter(NewName %in% GDA_auto$NewName)
categ_dis = categ_dis[match(V(g_sep)$name, categ_dis$NewName),]

V(g_sep)$value <- categ_dis$value

dis_sep_viz <- ggraph(g_sep, "fr") +
  geom_edge_hive(aes(width = weight), color = "grey45", alpha = 0.8) +
  geom_node_point(aes(size = degree, color = value)) +
  geom_node_text(aes(label = name, size = 7), nudge_y = 0.08) +
  scale_edge_width(range = c(0.1, 1)) +
  scale_color_hue(l  = c(75), c = 35) + 
  scale_edge_width(range = c(0.5, 3))+
  scale_size(range = c(2, 8)) + 
  theme_void() +
  theme(legend.text = element_text(size=18), legend.title = element_text(size = 20))

pdf("Autoimmune_separation.pdf", width = 29, height = 16)
print(dis_sep_viz)
dev.off()

```

```{r}
#signif_dis <- autoimmune_LCC_df %>% filter(signif == "signif")
#signif_dis <- unique(as.character(signif_dis$Disease))

g_signif_LCC_sep = delete_vertices(g_sep, V(g_sep)$name %ni% signif_dis)
isolated = which(degree(g_signif_LCC_sep)==0)
g_signif_LCC_sep = delete.vertices(g_signif_LCC_sep, isolated)

ggraph(g_signif_LCC_sep, 'stress') +
  geom_edge_hive(aes(width = weight,
                    alpha = weight)) +
  geom_node_point(aes(size = degree, color = value)) +
  geom_node_text(aes(label = name),
                 size = 3) +
  scale_edge_width(range = c(0.1, 1)) +
  scale_color_hue(l  = c(75), c = 35) + 
  scale_edge_width(range = c(0, 3))+
  scale_size(range = c(2, 8)) + 
  theme_void()
```





## Add LCC size to Jaccard similarity graph
```{r}
# Jaccard similarity graph with node size as the LCC size

jacc_dis = NetSci::Jaccard(GDA_auto)
jacc_dis$Node.1 <- as.character(jacc_dis$Node.1)
jacc_dis$Node.2 <- as.character(jacc_dis$Node.2)
jacc_dis$Jaccard.Index <- as.numeric(jacc_dis$Jaccard.Index)

jacc_dis_g <- graph.data.frame(jacc_dis)
jacc_dis_mat <- as.matrix(get.adjacency(jacc_dis_g, attr='Jaccard.Index'))
jacc_dis_mat_full <- jacc_dis_mat + t(jacc_dis_mat) + diag(dim(jacc_dis_mat)[1])

superheat(jacc_dis_mat_full, pretty.order.rows = T, pretty.order.cols=T, scale=F, 
          heat.pal = c("white", "red"), heat.pal.values = c(0, 0.07, 1), 
          bottom.label.text.angle = 90, bottom.label.text.size = 2, left.label.text.size = 2)

# Jacc as a graph
g_jacc = graph_from_adjacency_matrix(jacc_dis_mat_full, mode = "undirected", weighted = TRUE)

E(g_jacc)$width = E(g_jacc)$weight
V(g_jacc)$size = strength(g_jacc)
V(g_jacc)$label.color = "#264660"
E(g_jacc)$color = "grey66"

Isolated = which(degree(g_jacc) == 0)
g_jacc = delete.vertices(g_jacc, Isolated)
```


```{r}
# Statistical signif of overlaps
disease_pairs <- unique(GDA_auto$NewName)
col_labels <- c("dis1", "dis2", "weight")
hyper_dis_df <- data.frame(matrix(ncol = 3, nrow = 0))
colnames(hyper_dis_df) <- col_labels

for(i in 1:(length(disease_pairs)-1)){
  for(j in (i+1):length(disease_pairs)){
    
    genes_i <- unique(GDA_auto[which(GDA_auto$NewName == disease_pairs[i]),][2])
    genes_j <- unique(GDA_auto[which(GDA_auto$NewName == disease_pairs[j]),][2])
    all_genes <- unique(rbind(genes_i, genes_j))
    
    universe_success <- intersect(genes_i, genes_j)
    q <- dim(universe_success)[1] / dim(all_genes)[1]
    universe_failure <- all_genes[!(all_genes %in% universe_success)]
    size_collected <- dim(all_genes)[1]
    
    temp <- c(disease_pairs[i], disease_pairs[j], 
              Hypergeometric.test(q, dim(universe_success)[1], dim(universe_failure)[1], size_collected))
    hyper_dis_df[nrow(hyper_dis_df)+1,] <- temp
    
  }
}

hyper_dis_df$dis1 <- as.character(hyper_dis_df$dis1)
hyper_dis_df$dis2 <- as.character(hyper_dis_df$dis2)
hyper_dis_df$weight <- as.numeric(hyper_dis_df$weight)
```


```{r}
# Remove edges that are not signif

# make hyper_dis_df into a graph
hyper_dis_df <- hyper_dis_df %>% 
  mutate(padj = p.adjust(weight, method = "fdr")) %>%
  mutate(signif = ifelse(padj < 0.05, "padj < 0.05", "padj > 0.05"))

signif_link <- hyper_dis_df %>% filter(padj < 0.05) %>% select(dis1, dis2)
hyper_g <- graph_from_edgelist(as.matrix(signif_link), directed = F)

# get edges
gsize(hyper_g)
keep_edges = E(hyper_g)

# keep edges from jacc_dis_g that are in hyper_g
g_jacc_signif <- subgraph.edges(g_jacc, eids = which(E(g_jacc) %in% E(hyper_g)), delete.vertices = TRUE)
gsize(g_jacc_signif)

E(g_jacc_signif)$width = E(g_jacc_signif)$weight
#V(g_jacc_signif)$size = strength(g_jacc_signif) # change to LCC size
V(g_jacc_signif)$label.color = "#264660"
E(g_jacc_signif)$color = "grey66"

temp_df <- igraph::as_data_frame(g_jacc_signif, 'both')

require(ggraph)
ggraph(g_jacc_signif, 'stress') +
  geom_edge_hive(aes(width = weight, alpha = weight)) +
  geom_node_point(aes(size = size), color = "tomato3") +
  geom_node_text(aes(label = name, size = size)) +
  scale_edge_width(range = c(0.2, 1)) +
  theme_void()

```














