---
title: "2.0.2_Autoimmune_TissueHomogen"
author: "Ursula Widocki"
date: "9/30/2021"
output: html_document
---

```{r}
rm(list=ls())
```

```{r}
library(tidyverse)
library(data.table)
`%ni%` <- Negate(`%in%`)
library(igraph)
library(superheat)
library(corrplot)
library(patchwork)
source("/Users/ursulawidocki/Desktop/BarabasiLab/NetMedTools.R")
```

```{r}
## Read in PPI data
ppi <- read.csv('/Users/ursulawidocki/Desktop/BarabasiLab/Vaccine/Data/PPI_Symbol_Entrez.csv')
ppi_df <- ppi[,c("Symbol_A", "Symbol_B")]

ppi_df = ppi_df[!(!is.na(ppi_df$Symbol_B) & ppi_df$Symbol_B ==""), ]
ppi_df = ppi_df[!(!is.na(ppi_df$Symbol_A) & ppi_df$Symbol_A ==""), ]

ppi_df$value = 1
ppi_df = ppi_df %>% unique()
ppi_g <- igraph::graph_from_data_frame(ppi_df, directed = F)
ppi_g <- simplify(ppi_g)

ppi_degree_df = data.frame(Degree = degree(graph = ppi_g)) %>%
  mutate(Gene = row.names(.))

## Read in gene-disease assoc data
GDA_data = read.table("/Users/ursulawidocki/Desktop/BarabasiLab/Data/GDA_auto.csv", 
                      sep = ",", stringsAsFactors = F, header = T) # has isAutoimmune col
# select disease that have some form of Strong or Weak evidence and have more than 5 disease genes
GDA_auto = GDA_data %>%
  filter(Strong > 0 | 
           Weak > 0) %>%
  filter(hgnc_symbol %in% V(ppi_g)$name)%>% 
  group_by(NewName) %>%
  mutate(Total_Genes = n()) %>%
  filter(Total_Genes > 5) %>%
  filter(isAutoimmune == 1) %>%
  dplyr::select(NewName, hgnc_symbol) %>%
  unique()

## Read in tissue data
tissue_dat <- read.table("/Users/ursulawidocki/Desktop/BarabasiLab/Data/Edited_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct.txt", sep = "\t", stringsAsFactors = F, header = T)
# filter out genes that are not assoc with any diseases
tissue_dat <- tissue_dat %>% select(-Name) %>% filter(Description %in% V(ppi_g)$name)

## Read in Immune System Gene Data
immune_data = read.table("/Users/ursulawidocki/Desktop/BarabasiLab/Data/immunity_genes_all.tsv", 
                         sep = "\t", stringsAsFactors = F, header = T, row.names = 1)
immune_data <- immune_data %>% # remove ReactomeDB
  select(!c(ReactomePathwayInnate, ReactomePathIDInnate, ReactomeDB, isInnateReactome, ReactomePathwayAdaptive, ReactomePathIDAdaptive, isAdaptiveReactome))
```

```{r}
# maybe I want this function
tissueScore <- function(tissue_data, dis_genes, disease_name){
  # tissue_data is a df with genes in the leftmost col
  # calculates the number of genes n^j_i expressed in each tissue j
  
  
  # returns df of cols: diseasename, tissuename1, ..., tissuename54, tissueScore
}
```

```{r}
# Calculates tissue homogeneity of the diseases
#  TH_i = max_j[ n^j_i / n_i ]         where i = disease and j = tissue
####### ------>  maybe also store the tissues where this max occurs #########

autoimmune_dis <- unique(GDA_auto$NewName)
tissues <- colnames(tissue_dat)[-1]

col_labels <- c(tissues, "max")
tissueScores_df <- data.frame(matrix(ncol = length(col_labels), nrow = length(autoimmune_dis))) # store disease and its tissue scores and max
colnames(tissueScores_df) <- col_labels
rownames(tissueScores_df) <- autoimmune_dis

# for each disease
for(dis in autoimmune_dis){
  dis_genes <- GDA_auto %>% filter(NewName == dis)
  dis_genes <- unique(dis_genes$hgnc_symbol)
  
  for(t in tissues){
    # get disease genes that are in tissue t
    tiss_subset <- tissue_dat %>%
      select(c("Description", t)) %>%
      filter(Description %in% dis_genes)
    
    n_i <- length(unique(tiss_subset$Description)) # number of dis 
    temp <- tiss_subset[which(tiss_subset[,2] > 5),]
    nj_i <- length(unique(temp[,2]))
    
    tissueHomogen <- nj_i / n_i
    tissueScores_df[dis, t] <- tissueHomogen
    
  }
  
  tissueScores_df[dis, "max"] <- max(tissueScores_df[dis, 1:length(tissues)])
  #print(max(tissueScores_df[dis, 1:length(tissues)]))  ########### debug
  
}

```

```{r}
# get distribution for tissue homogeniety for each disease

iter = 1000 # should be 10^5
numTissueGenes <- dim(tissue_dat)[1]

col_labels <- c("p_val")
tissHomo_pval <- data.frame(matrix(ncol = length(col_labels), nrow = length(autoimmune_dis))) 
colnames(tissHomo_pval) <- col_labels
rownames(tissHomo_pval) <- autoimmune_dis

for(dis in autoimmune_dis){ # for each disease
  print(dis) ######## debug
  distrib <- c()
  # pick the same number of genes randomly in tissue_dat$Description
  dis_genes <- GDA_auto %>% filter(NewName == dis)
  num_dis_genes <- length(unique(dis_genes$hgnc_symbol))
  
  # make the distribution
  for(i in seq(1:iter)){ # up to 10^5 times
    #print(paste0("iter: ", i)) ####### debug
    rand_ind <- sample(1:numTissueGenes, num_dis_genes, replace=F)
    rand_genes <- tissue_dat$Description[rand_ind]
    temp_tissueScores <- c() # stores tissue ratios 
    
    # calc tissuehomogeneity
    for(tissue in tissues){
      tiss_subset <- tissue_dat %>%
        select(c("Description", tissue)) %>%
        filter(Description %in% rand_genes)
      
      n_i <- length(unique(tiss_subset$Description))
      temp <- tiss_subset[which(tiss_subset[,2] > 5),]
      nj_i <- length(unique(temp[,2]))
      
      tissueHomogen <- nj_i / n_i
      temp_tissueScores <- c(temp_tissueScores, tissueHomogen)
      
    }
    # store max in distrib
    distrib <- c(distrib, max(temp_tissueScores))
    
  }
  # calc p val
  p_val <- calc_p_val(distrib, tissueScores_df[dis, "max"])
  tissHomo_pval[dis,] <- p_val$p_ut
}



```
```{r}
tissHomo_pvals <- cbind(tissueScores_df$max, tissHomo_pval)
tissHomo_pvals$NewName <- rownames(tissHomo_pvals)

tissHomo_df <- GDA_auto %>%
  group_by(NewName) %>%
  summarize(num_genes = n())
tissHomo_df <- merge(tissHomo_df, tissHomo_pvals, by = "NewName")
colnames(tissHomo_df)[3] <- "max"

tissHomo_df <- tissHomo_df %>% 
  mutate(padj = p.adjust(p_val, method = "fdr")) %>%
  mutate(signif = ifelse(padj < 0.05, "padj < 0.05", "padj > 0.05"))

#tissHomo_df$signif <- ifelse(tissHomo_df$padj < 0.05, "signif", "nonsignif")

#tissHomo_df %<>% arrange(num_genes)
#tissHomo_df$Disease = factor(row.names(tissHomo_df), levels = row.names(tissHomo_df))

ggplot(tissHomo_df) +
  aes(x = reorder(NewName, max), y = max, colour = signif, size = max) +
  geom_point(shape = "circle", fill = "turquoise3", alpha = 0.4) +
  scale_color_hue(direction = 1) +
  scale_color_manual(values = c("padj < 0.05" = "turquoise3", "padj > 0.05" = "tomato1")) +
  labs(x = "Disease", y = "Tissue Homogeneity", title = "Tissue Homogeneity of Autoimmune Diseases") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  coord_flip()


#ggplot(tissHomo_df %>% dplyr::arrange(p_val)) +
#  aes(x = reorder(NewName, -p_val), y = p_val, colour = signif, size = max) +
#  geom_point(shape = "circle", fill = "#112446", alpha = 0.4, color = signif) +
#  labs(x = "Disease", y = "Tissue Homogeneity", title = "Tissue Homogeneity of Autoimmune Diseases") +
#  #scale_color_hue(direction = 1) +
#  scale_y_log10() +
#  ylim(0, 7.5) +
#  theme_minimal() +
#  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
#  geom_hline(yintercept = -log10(0.05), color = "red")

```

```{r}
# Calculate if non-immune genes of diseases make an LCC

autoimmune_LCC_df = read.table("/Users/ursulawidocki/Desktop/BarabasiLab/Data/AutoDis_LCCs.tsv", 
                               sep = "\t", stringsAsFactors = F, header = T)
rownames(autoimmune_LCC_df) <- autoimmune_LCC_df$Disease

autoimmune_LCC_df <- autoimmune_LCC_df %>% 
  mutate(padj = p.adjust(p_val, method = "fdr")) %>%
  mutate(signif = ifelse(padj < 0.05, "padj < 0.05", "padj > 0.05"))

signif_dis <- autoimmune_LCC_df %>%
  filter(padj < 0.05)
signif_dis <- signif_dis$Disease

col_labels <- c("Disease", "LCCsize", "p_val", "Mean", "SD", "Z", "num_genes")
non_immune_LCC_df <- data.frame(matrix(ncol = length(col_labels), nrow = 0))
colnames(non_immune_LCC_df) <- col_labels

for(dis in signif_dis){
  dis_genes <- GDA_auto %>% filter(NewName == dis) # get dis genes
  dis_genes <- unique(dis_genes$hgnc_symbol)
  
  not_immune <- dis_genes[dis_genes %ni% immune_data$Symbol]
  not_immune <- not_immune[not_immune %in% V(ppi_g)$name]
  non_immune_LCC <- LCC_signif(G = ppi_g, targets = not_immune, num_bins_degree_G = 1, min_bin_degree = 20, iter = 1000)
  
  # add info to df
  new_line <- c(dis, non_immune_LCC$size, non_immune_LCC$p_val, non_immune_LCC$emp_mean, 
                non_immune_LCC$emp_SD, non_immune_LCC$Z, length(dis_genes))
  non_immune_LCC_df[nrow(non_immune_LCC_df) + 1,] <- new_line
  
}

```

```{r}
non_immune_LCC_df$LCCsize <- as.numeric(non_immune_LCC_df$LCCsize)
non_immune_LCC_df$p_val <- as.numeric(non_immune_LCC_df$p_val)
non_immune_LCC_df$Mean <- as.numeric(non_immune_LCC_df$Mean)
non_immune_LCC_df$SD <- as.numeric(non_immune_LCC_df$SD)
non_immune_LCC_df$Z <- as.numeric(non_immune_LCC_df$Z)
non_immune_LCC_df$num_genes <- as.numeric(non_immune_LCC_df$num_genes)

non_immune_LCC_df <- non_immune_LCC_df %>% 
  mutate(padj = p.adjust(p_val, method = "fdr")) %>%
  mutate(signif = ifelse(padj < 0.05, "padj < 0.05", "padj > 0.05"))

rownames(non_immune_LCC_df) <- non_immune_LCC_df$Disease

non_immune_LCC_df %<>% arrange(desc(padj))
non_immune_LCC_df$Disease = factor(row.names(non_immune_LCC_df), 
                                   levels = row.names(non_immune_LCC_df))

ggplot(non_immune_LCC_df %>% dplyr::arrange(p_val)) +
  aes(x = Disease, y = -log10(p_val), colour = signif, size = LCCsize) +
  geom_point(shape = "circle", fill = "#112446", alpha = 0.4) +
  labs(x = "Disease", y = "-log10 p-value", title = "Autoimmune Diseases and Modules formed by Non-Immune System genes") +
  scale_color_hue(direction = 1) +
  scale_color_manual(values = c("padj < 0.05" = "turquoise3", "padj > 0.05" = "tomato1")) +
  scale_y_log10() +
  #ylim(0, 7.5) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  geom_hline(yintercept = -log10(0.05), color = "red")

ggplot(non_immune_LCC_df %>% dplyr::arrange(desc(padj))) +
  aes(x = Disease, y = -log10(padj), colour = signif, size = LCCsize) +
  geom_point(shape = "circle", fill = "tomato1", alpha = 0.4,) +
  labs(x = "Disease", y = "-log10 adj p-value", title = "Autoimmune Diseases and Modules formed by Non-Immune System genes") +
  scale_color_hue(direction = 1) +
  scale_y_log10() +
  #ylim(0, 7.5) +
  scale_color_manual(values = c("padj < 0.05" = "turquoise3", "padj > 0.05" = "tomato1")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  geom_hline(yintercept = -log10(0.05), color = "red") + 
  coord_flip()

```



```{r}
# Save the LCC output
#write.table(final_LCCs, "/Users/ursulawidocki/Desktop/BarabasiLab/Data/AutoDis_Tissue_LCCs.tsv", sep = "\t", row.names = T, col.names = T)

final_LCCs <- fread("/Users/ursulawidocki/Desktop/BarabasiLab/Data/AutoDis_Tissue_LCCs.tsv")
```








################# Code I'm not using here
```{r}
data <- final_LCCs
data %<>%
  mutate(padj = p.adjust(LCC_p, method = "fdr")) %>%
  mutate(prop_lcc = (LCC_size/Disease_Tissue_Genes)*100) %>%
  mutate(Ps = ifelse(padj < 0.05, "padj < 0.05", "padj > 0.05")) %>%
  mutate(shape = ifelse(padj < 0.05, 1, 4))
# Clean up tissue names in data
data$Tissue = data$Tissue %>%
  stringr::str_replace_all(., "\\.", " ") %>%
  stringr::str_squish()
data %<>% filter(Tissue %ni% c("Cells EBV transformed lymphocytes", "Cells Cultured fibroblasts"))

```

```{r}
# plot the LCCs of dis in tissues

# correlogram kind of scatterplot of LCCs of dis in tissues
p1 <- data %>%
  filter(Disease_Name %in% signif_dis) %>%
  ggplot() +
  aes(x = Disease_Name, 
      y = Tissue, 
      color = prop_lcc,
      size = prop_lcc,
      shape = Ps) +
  geom_point() +
  scale_color_distiller(palette = "YlGnBu", 
                        direction = 1) +
  scale_shape_manual(values = c(16, 4)) +
  scale_size(range = c(0.1, 4)) + 
  labs(x = "Autoimmune Disease") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90), 
        legend.position = "bottom", 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())

# Disease bar plot
temp <- data %>%
  filter(Disease_Name %in% signif_dis) %>% 
  filter(padj < 0.05) %>% # neutropenia dropped here
  group_by(Disease_Name) %>% 
  dplyr::summarise(n=n())
# neutropenia is getting filtered out since no signif LCCs, so we need to add it back
temp <- rbind(temp, c("neutropenia", 0)) %>% as.data.frame()
temp$n <- as.integer(temp$n)

p3 <- temp %>%
  ggplot() +
  aes(x = Disease_Name, y = n) +
  geom_bar(fill = "#122265", stat = "identity") + #position = position_dodge(preserve = "single")
  theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(y = "LCC count")


# Tissue bar plot
p2 <- data %>%
  filter(Disease_Name %in% signif_dis) %>% 
  filter(padj < 0.05) %>% 
  group_by(Tissue) %>% 
  dplyr::summarise(n=n()) %>%
  ggplot() +
  aes(x = Tissue, weight = n) +
  geom_bar(fill = "#122265") + # "#333366"
  labs(y = "LCC count") +
  theme_minimal() +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +

  coord_flip()

# patchwork things together
((p3 + plot_spacer() + plot_layout(widths = c(5,1))) / ((p1 + p2) + plot_layout(widths = c(5,1))))+ plot_layout(heights = c(1,6))

```

